config/routes.rb
OfertasLaborales::Application.routes.draw do
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.xml
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.xml
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false }  # show.html.erb
      format.xml  { render :xml => @job }
	  
    end
	
  end

  # GET /jobs/new
  # GET /jobs/new.xml
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.xml
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to(@job, :notice => 'Job was successfully created.') }
        format.xml  { render :xml => @job, :status => :created, :location => @job }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.xml
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to(@job, :notice => 'Job was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.xml
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to(jobs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
	function job_validate_field(element, min_length, max_length){
		var value = element.val();
		if (value.length < min_length){
			element.css("border-color","red");
			alert("El campo ingresado es demasiado corto");
} else if ( value.length > max_length){
			element.css("border-color","red");
			alert("El campo ingresado es demasiado largo");
}
}
	jQuery("#job_title").blur(function(){
	job_validate_field(jQuery(this), 6, 30);
});


</script>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Company</th>
    
  </tr>
<% $num = 0 %>
<% @jobs.each do |job| %>
  <tr>
    <% $num= $num + 1%>
	<td id=<%= $num %>><%= link_to job.title, job_path(job.id),:class => "links" %></td>
    <td><%= job.company %></td>
  
    
  </tr>
<% end %>
</table>
<div id="caja"></div>
<br />

<%= link_to 'New Job', new_job_path %>
<script>
jQuery(".links").click(function(){
var link = jQuery(this).attr('href');
jQuery.ajax({
cache:false,
url: link,
success :function(data){
jQuery('#caja').html(data);
},
error: function(){
alert('ocurrio un error' );
}

});
return false;
});
</script>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @job.title %>
</p>

<p>
  <b>Company:</b>
  <%= @job.company %>
</p>

<p>
  <b>Email:</b>
  <%= @job.email %>
</p>

<p>
  <b>Salary:</b>
  <%= @job.salary %>
</p>

<p>
  <b>Description:</b>
  <%= @job.description %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OfertasLaborales</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag "jobs.css" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>